// Selectors below were captured live from the app (autos@sanu.netsferetest.org,
// "HOPT_Sanity_Group" conversation) rather than guessed:
//  - The right-hand "Conversation Details" panel is visible by default next to
//    an open conversation; the header ion-information-circled icon re-opens it
//    if a narrower layout ever hides it.
//  - Its "Actions" list has plain text rows: Documents / Summarize / Favorite / Mute.
//  - Clicking "Summarize" expands 4 period rows: "Generate 1 day/1 week/2 week/4 week Summary".
//    The 1-day row has a stable id: generate-conversation-day-1.
//  - Clicking a period opens a summary card (heading "<name> Summary", "Generated
//    by Net-C", the chosen period, a timestamp) that shows "Generating Summary"
//    with "We will notify you when it is ready." until the AI text is ready, then
//    "Back to Conversation" / "Forward" / "Copy" actions.
//  - Scrolling the details panel further down shows "<n> People in this
//    conversation" followed by each participant's name and role (e.g. "owner").
//  - Once ready, the generated text itself renders inside a
//    <span class="summary-bubble"> ("Summary: ... Action Items: ...").
export default class ConversationDetailsPageLocator {
  constructor(page) {
    this.page = page;

    this.infoButton = page.locator('span.icon.ion-information-circled').first();
    this.detailsPanelHeading = page.locator('text=/Conversation ID/i').first();

    this.documentsAction = page.locator("//div[text()='Documents']");
    this.summarizeAction = page.locator("//div[text()='Summarize']");
    this.summaryPendingLabel = page.locator("//div[text()='Summary Pending']");
    this.favoriteAction = page.locator("//div[text()='Favorite']");
    this.muteAction = page.locator("//div[text()='Mute']");

    this.oneDaySummaryOption = page.locator('#generate-conversation-day-1')
      .or(page.locator('//div[contains(text(),"Generate 1 day Summary")]'));

    this.summaryGeneratingIndicator = page.locator('text=Generating Summary').first();
    this.summaryNotifyLabel = page.locator('text=/We will notify you when it is ready/i').first();
    this.summaryGeneratedByLabel = page.locator('text=/Generated by Net-C/i').first();
    this.backToConversationButton = page.locator('text=Back to Conversation').first();
    this.summaryCopyButton = page.locator('text=Copy').first();
    this.summaryBubble = page.locator('.summary-bubble, [class*="summar" i]').first();
    // Same text renders both as the clickable menu row (before generation)
    // and as a label echoed back inside the finished summary card — matching
    // either confirms the request/result is scoped to the 1-day period.
    this.oneDaySummaryPeriodLabel = page.locator('text=/Generate 1 day Summary/i').first();

    this.editParticipantsLabel = page.locator("//div[text() = 'Edit Participant(s)']");
    this.participantCountLabel = page.locator('text=/\\d+ People in this conversation/i');
  }
}
